---
- name: Create node configurations.
  template:
    src: templates/{{ item.1 }}_template.j2
    dest: "{{ location }}/{{ item.1 }}_{{ item.0.name }}.cfg"
  vars:
    side: "{{ item.0.end }}"
  loop: "{{ site_list|product(job)|list }}"
  loop_control:
    label: "{{ item.0.name }} and {{ item.1 }} create Config from EVI {{ FF_start_evi_ID }} to EVI {{ FF_end_evi_ID }}"
  delegate_to: "localhost"
  run_once: true
  tags: create_config,create_xc_service,create_ELAN_service,delete_xc_service,delete_ELAN_service,config_policy,delete_policy
# tasks file for /root/Dansi/jinja/roles/create_config
# dfre1