---
all:
  children:
    # NCS_BLR:
    #   children:
    #     Aend:
    #      hosts:
    #        AR5:
    #          ansible_host: "10.91.126.115"
    #     Bend:
    #      hosts:
    #         AR6:
    #           ansible_host: "10.91.126.116"
    #   vars:
    #     ansible_ssh_pass: "N0@ught33b0y"
    #     ansible_network_os: "iosxr"
    #     ansible_ssh_user: "dshaw1"
    #     ansible_pyhton_interpreter: "/usr/bin/env python3"
    NCS_BLR:
      children:
        Aend:
         hosts:
           AR13:
             ansible_host: "10.91.126.199"
        Bend:
         hosts:
            AR14:
              ansible_host: "10.91.126.200"
      vars:
        ansible_ssh_pass: "N0@ught33b0y"
        ansible_network_os: "iosxr"
        ansible_ssh_user: "dshaw1"
        ansible_pyhton_interpreter: "/usr/bin/env python3"