- hosts: AR14
  connection: network_cli
  gather_facts: no
  roles:
    - ansible-pyats
  tasks:
    - pyats_parse_command:
        command: 'show ethernet cfm peer meps'
      register: output
    - debug: var=output.structured
    # - set_fact:
    #     SOFT_VERSION : "{{ output.structured.instance.all.vrf.default.neighbor.'10.91.126.102'}}"
    # - name: verify 
    #   assert:
    #     that:
    #       - SOFT_VERSION == '6.6.3'
    #     fail_msg: "'SOFT_VERSION' is not ok"
    #     success_msg: "'SOFT_VERSION' is ok"