---
- name: get the location of Operation
  hosts: NCS_BLR,localhost
  gather_facts: false
  tags: create_config,create_xc_service,create_ELAN_service,delete_xc_service,delete_ELAN_service,config_policy,delete_policy,test,delete_xc_service_CORE1,create_xc_service_CORE1,configure_policy
  vars:
    Parent_Location: 'absent'
  tasks:
  - block:
      - shell:
          cmd: pwd
        register: locator 
      - set_fact:
          Parent_Location: "{{ locator.stdout }}"
    run_once: true
    delegate_to: "localhost"

- hosts: NCS_BLR
  gather_facts: False
  roles:
    - create_config

- name: ELAN service Creation
  hosts: NCS_BLR
  connection: network_cli
  gather_facts: false
  tasks:
  - name: "configure policy One time"
    napalm_install_config:
      config_file: "{{ location }}{{ item.1 }}_{{ item.0.name }}.cfg"
      provider: "{{ napalm_provider }}"
      commit_changes: True
      replace_config: False
    loop: "{{ site_list|product(configure_policy_job)|list }}"
    when: item.0.name == local_hostname
    loop_control:
      label: "{{ item.0.name }} and {{ item.1 }} from EVI {{ FF_start_evi_ID }} to EVI {{ FF_end_evi_ID }}"
    tags: configure_policy