---
- name: get the location of Operation
  hosts: AR13
  gather_facts: false
  connection: network_cli
  tasks:
  - iosxr_command:
      host: "{{ ansible_host }}"
      username: '{{ ansible_ssh_user }}'
      commands: 
          - show ethernet cfm services domain COLT-1 service {{ ANE_ID }}-{{ BNE_ID}}_DIP_FF_{{ item }}
      match: all
      wait_for:
          - result[0] contains "all operational, no errors"        
    register: output
    loop_control:
      label: "*****************************************************************************
      {{ output.stdout_lines | to_nice_yaml}} "
      #pause: 3
    with_sequence: start="{{ FF_start_evi_ID }}" end="{{ FF_end_evi_ID }}" stride="1"

#show ethernet sla statistics interface gigabitEthernet 0/0/0/11.99 profile DMM2